services:
  searxng:
    image: searxng/searxng
    restart: always

    ports:
      - "${SEARXNG_PORT}:8080"
    environment:
      - BASE_URL=http://0.0.0.0:2946
      - INSTANCE_NAME=the-index
    volumes:
      - ./searxng/:/etc/searxng

  litellm:
    image: ghcr.io/berriai/litellm:main-v1.82.6-nightly
    restart: always
    ports:
      - ${LITELLM_PORT}:4000
    environment:
      - DASHSCOPE_API_KEY=${DASHSCOPE_API_KEY}
      - LITELLM_API_KEY=${LITELLM_API_KEY}
    volumes:
      - ./litellm/config.yaml:/app/config.yaml
    command: ["--config", "/app/config.yaml"]

volumes:
  database_data:
    driver: local
