"""GENERATED from crow-memory-types/schema.json — do not edit by hand.

Regenerate: uv --project crow-memory-sdk run python scripts/gen_wire_types.py
Source of truth: the rust structs in crow-memory-types/src/lib.rs.
"""

# generated by datamodel-codegen:
#   filename:  schema.json

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field, RootModel, conint


class AddImageRequest(BaseModel):
    data: str = Field(
        ..., description='Base64-encoded image bytes (RFC 4648 standard alphabet).'
    )
    h: int
    mime: str
    w: int


class AddMessageRequest(BaseModel):
    agent_id: str
    message: Any
    usage: Any | None = None


class AddMessageResponse(BaseModel):
    id: int


class AgentRecord(BaseModel):
    agent_id: str
    agent_idx: int
    created_at: str
    cwd: str
    model_identifier: str
    prompt_args: Any
    prompt_id: str
    request_params: Any
    session_id: str
    status: str
    system_prompt: str
    tool_definitions: Any


class CreateAgentRequest(BaseModel):
    agent_id: str
    agent_idx: int
    cwd: str
    model_identifier: str
    prompt_args: Any
    prompt_id: str
    request_params: Any
    session_id: str
    system_prompt: str
    tool_definitions: Any


class ErrorResponse(BaseModel):
    error: str


class ImageRecord(BaseModel):
    created_at: str
    data: str = Field(
        ..., description='Base64-encoded image bytes (RFC 4648 standard alphabet).'
    )
    h: int
    image_id: str
    mime: str
    w: int


class LookupPromptRequest(BaseModel):
    name: str
    template: str


class LookupPromptResponse(BaseModel):
    prompt_id: str


class MaxAgentIdxResponse(BaseModel):
    max_idx: int


class MessageRecord(BaseModel):
    agent_id: str
    created_at: str
    data: Any
    id: int
    role: str
    score: float | None = Field(
        None,
        description='Search relevance (lower = better, LanceDB `_distance`); only set on\nsemantic search hits.',
    )


class PromptRecord(BaseModel):
    id: str
    name: str
    template: str


class SearchMessagesRequest(BaseModel):
    limit: conint(ge=0)
    query: str
    role: str | None = None


class SessionInfo(BaseModel):
    agent_count: conint(ge=0)
    agent_idxs: list[int] | None = Field(
        [], description='Sorted distinct agent_idx values in this session.'
    )
    cwd: str
    last_activity: str
    last_message: MessageRecord | None = Field(
        None, description='The most recent message in the session, if any.'
    )
    last_role: str
    message_count: conint(ge=0)
    model_identifier: str
    session_id: str