model_list:
  - model_name: qwen3.5-plus
    litellm_params:
      model: dashscope/qwen3.5-plus
      api_base: https://coding-intl.dashscope.aliyuncs.com/v1
      api_key: os.environ/DASHSCOPE_API_KEY

  - model_name: qwen3.6-plus
    litellm_params:
      model: dashscope/qwen3.6-plus
      api_base: https://coding-intl.dashscope.aliyuncs.com/v1
      api_key: os.environ/DASHSCOPE_API_KEY

general_settings:
  master_key: os.environ/LITELLM_API_KEY
